GET https://api.discogs.com/database/search?q=IsThisIt&token=KbEizCiUnPDWhSjCmJvqBZvnzWnlfYtFKEQcGQEf HTTP/1.1

Content-Type: application/json
Authorization: token KbEizCiUnPDWhSjCmJvqBZvnzWnlfYtFKEQcGQEf
